version: '3.5'

services:
  app:
    build:
      context: .
    restart: always
    command: npm start
    volumes:
      - ./:/app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - ./secrets:/run/secrets
    ports:
      - 3000:3000
    environment:
      DOCKER_USERNAME: _json_key
      DOCKER_REGISTRY: eu.gcr.io
